#!/bin/bash
script_dir=$( dirname -- "$( readlink -f -- "$0"; )"; )
pushd $script_dir

layout_log=./anyitem-cloud/layout-log.$(date '+%Y%m%d.%H%M%S').txt

input_csv=./anyitem-cloud/anyitemcloud-import.layout.csv
output_directory=./anyitem-cloud
image_type=png

layout_anyitemcloud \
    -i $input_csv \
    -output_directory $output_directory \
    -output_image_format $image_type \
    -maximize_empty_space \
    -show_itemcloud \
    -show_itemcloud_reservation_chart \
    -log_filepath $layout_log

popd