from enum import Enum

class FontUsageCategory(Enum):
    CUSTOM = 0
    MOBILE_INTERACTION_HEAVY = 1
    MOBILE_TEXT_HEAVY = 2
    DESKTOP_INTERACTION_HEAVY = 3
    DESKTOP_TEXT_HEAVY = 4
    SECONDARY_MOBILE_INTERACTION_HEAVY = 5
    SECONDARY_MOBILE_TEXT_HEAVY = 6
    SECONDARY_DESKTOP_INTERACTION_HEAVY = 7
    SECONDARY_DESKTOP_TEXT_HEAVY = 8


class FontTypeCategories(Enum):
    CUSTOM = 0
    BOLD = 1
    SCRIPT = 2
    MONOSPACE = 3
    CLASSIC = 4
    MODERN = 5
    CLEAN = 6
