from itemcloud.size import RESIZE_TYPES
from itemcloud.item_cloud_defaults import MODE_TYPES
from itemcloud.util.search_types import SEARCH_PATTERNS
LAYOUT_MAX_ITEMS = 'layout_max_items'
LAYOUT_MAX_ITEMS_HELP = '<integer>'
LAYOUT_MIN_ITEM_SIZE_WIDTH = 'layout_min_item_size_width'
LAYOUT_MIN_ITEM_SIZE_WIDTH_HELP = '<width>'
LAYOUT_MIN_ITEM_SIZE_HEIGHT = 'layout_min_item_size_height'
LAYOUT_MIN_ITEM_SIZE_HEIGHT_HELP = '<height>'
LAYOUT_ITEM_STEP = 'layout_item_step'
LAYOUT_ITEM_STEP_HELP = '<integer>'
LAYOUT_ITEM_ROTATION_INCREMENT = 'layout_item_rotation_increment'
LAYOUT_ITEM_ROTATION_INCREMENT_HELP = '<integer>'
LAYOUT_RESIZE_TYPE = 'layout_resize_type'
LAYOUT_RESIZE_TYPE_HELP = '|'.join(RESIZE_TYPES)
LAYOUT_SCALE = 'layout_scale'
LAYOUT_SCALE_HELP = '<float>'
LAYOUT_MARGIN = 'layout_margin'
LAYOUT_MARGIN_HELP = '<image-margin>'
LAYOUT_NAME = 'layout_name'
LAYOUT_NAME_HELP = '<name>'
LAYOUT_TOTAL_THREADS = 'layout_total_threads'
LAYOUT_TOTAL_THREADS_HELP = '<integer>'
LAYOUT_LATENCY = 'layout_latency'
LAYOUT_LATENCY_HELP = '<string>'
LAYOUT_SEARCH_PATTERN = 'layout_search_pattern'
LAYOUT_SEARCH_PATTERN_HELP = '|'.join(SEARCH_PATTERNS)
LAYOUT_HEADERS = [
    LAYOUT_MAX_ITEMS,
    LAYOUT_MIN_ITEM_SIZE_WIDTH,
    LAYOUT_MIN_ITEM_SIZE_HEIGHT,
    LAYOUT_ITEM_STEP,
    LAYOUT_ITEM_ROTATION_INCREMENT,
    LAYOUT_RESIZE_TYPE,
    LAYOUT_SCALE,
    LAYOUT_MARGIN,
    LAYOUT_NAME,
    LAYOUT_TOTAL_THREADS,
    LAYOUT_LATENCY,
    LAYOUT_SEARCH_PATTERN
]
LAYOUT_HEADERS_HELP = [
    LAYOUT_MAX_ITEMS_HELP,
    LAYOUT_MIN_ITEM_SIZE_WIDTH_HELP,
    LAYOUT_MIN_ITEM_SIZE_HEIGHT_HELP,
    LAYOUT_ITEM_STEP_HELP,
    LAYOUT_ITEM_ROTATION_INCREMENT_HELP,
    LAYOUT_RESIZE_TYPE_HELP,
    LAYOUT_SCALE_HELP,
    LAYOUT_MARGIN_HELP,
    LAYOUT_NAME_HELP,
    LAYOUT_TOTAL_THREADS_HELP,
    LAYOUT_LATENCY_HELP,
    LAYOUT_SEARCH_PATTERN_HELP
]
LAYOUT_CANVAS_SIZE_WIDTH = 'layout_canvas_size_width'
LAYOUT_CANVAS_SIZE_WIDTH_HELP = '<width>'
LAYOUT_CANVAS_SIZE_HEIGHT = 'layout_canvas_size_height'
LAYOUT_CANVAS_SIZE_HEIGHT_HELP = '<height>'
LAYOUT_CANVAS_MODE = 'layout_canvas_mode'
LAYOUT_CANVAS_MODE_HELP = '|'.join(MODE_TYPES)
LAYOUT_CANVAS_BACKGROUND_COLOR = 'layout_canvas_background_color'
LAYOUT_CANVAS_BACKGROUND_COLOR_HELP = '<empty>|<any-color-name>'
LAYOUT_CANVAS_NAME = 'layout_canvas_name'
LAYOUT_CANVAS_NAME_HELP = '<name>'
LAYOUT_CANVAS_RESERVATION_MAP_FILEPATH = 'layout_canvas_reservation_map_csv_filepath'
LAYOUT_CANVAS_RESERVATION_MAP_FILEPATH_HELP = '<csv-filepath-of-reservation_map>'
LAYOUT_CANVAS_HEADERS = [
    LAYOUT_CANVAS_NAME,
    LAYOUT_CANVAS_MODE,
    LAYOUT_CANVAS_BACKGROUND_COLOR,
    LAYOUT_CANVAS_SIZE_WIDTH,
    LAYOUT_CANVAS_SIZE_HEIGHT,
    LAYOUT_CANVAS_RESERVATION_MAP_FILEPATH
]
LAYOUT_CANVAS_HEADER_HELP = [
    LAYOUT_CANVAS_NAME_HELP,
    LAYOUT_CANVAS_MODE_HELP,
    LAYOUT_CANVAS_BACKGROUND_COLOR_HELP,
    LAYOUT_CANVAS_SIZE_WIDTH_HELP,
    LAYOUT_CANVAS_SIZE_HEIGHT_HELP,
    LAYOUT_CANVAS_RESERVATION_MAP_FILEPATH_HELP
]

LAYOUT_CONTOUR_MASK_IMAGE_FILEPATH = 'layout_contour_mask_image_filepath'
LAYOUT_CONTOUR_MASK_IMAGE_FILEPATH_HELP = '<empty>|<filepath-of-image-used-as-mask>'
LAYOUT_CONTOUR_WIDTH = 'layout_contour_width'
LAYOUT_CONTOUR_WIDTH_HELP = '<float>'
LAYOUT_CONTOUR_COLOR = 'layout_contour_color'
LAYOUT_CONTOUR_COLOR_HELP = '<any-color-name>'
LAYOUT_CONTOUR_HEADERS = [
    LAYOUT_CONTOUR_MASK_IMAGE_FILEPATH,
    LAYOUT_CONTOUR_WIDTH,
    LAYOUT_CONTOUR_COLOR
]
LAYOUT_CONTOUR_HEADER_HELP = [
    LAYOUT_CONTOUR_MASK_IMAGE_FILEPATH_HELP,
    LAYOUT_CONTOUR_WIDTH_HELP,
    LAYOUT_CONTOUR_COLOR_HELP
]


LAYOUT_ITEM_FILEPATH = 'layout_item_filepath'
LAYOUT_ITEM_FILEPATH_HELP = '<filepath-of-item-to-render>'
LAYOUT_ITEM_POSITION_X = 'layout_item_position_x'
LAYOUT_ITEM_POSITION_X_HELP = '<x>'
LAYOUT_ITEM_POSITION_Y = 'layout_item_position_y'
LAYOUT_ITEM_POSITION_Y_HELP = '<y>'
LAYOUT_ITEM_SIZE_WIDTH = 'layout_item_size_width'
LAYOUT_ITEM_SIZE_WIDTH_HELP = '<width>'
LAYOUT_ITEM_SIZE_HEIGHT = 'layout_item_size_height'
LAYOUT_ITEM_SIZE_HEIGHT_HELP = '<height>'
LAYOUT_ITEM_ORIENTATION = 'layout_item_orientation'
LAYOUT_ITEM_ROTATED_DEGREES = 'layout_item_rotated_degrees'
LAYOUT_ITEM_ROTATED_DEGREES_HELP = '<degrees-rotation>'

LAYOUT_ITEM_RESERVATION_POSITION_X = 'layout_item_reserved_position_x'
LAYOUT_ITEM_RESERVATION_POSITION_X_HELP = '<x>'
LAYOUT_ITEM_RESERVATION_POSITION_Y = 'layout_item_reserved_position_y'
LAYOUT_ITEM_RESERVATION_POSITION_Y_HELP = '<y>'
LAYOUT_ITEM_RESERVATION_SIZE_WIDTH = 'layout_item_reserved_size_width'
LAYOUT_ITEM_RESERVATION_SIZE_WIDTH_HELP = '<width>'
LAYOUT_ITEM_RESERVATION_SIZE_HEIGHT = 'layout_item_reserved_size_height'
LAYOUT_ITEM_RESERVATION_SIZE_HEIGHT_HELP = '<height>'
LAYOUT_ITEM_RESERVATION_NO = 'layout_item_reservation_no'
LAYOUT_ITEM_RESERVATION_NO_HELP = '<empty>|<reservation_no_in_reservation_map>'
LAYOUT_ITEM_LATENCY = 'layout_item_latency'
LAYOUT_ITEM_LATENCY_HELP = '<string>'
LAYOUT_ITEM_TYPE = 'layout_item_type'
LAYOUT_ITEM_TYPE_HELP = '<name-of-subclassed-layout-type>'

LAYOUT_ITEM_HEADERS = [
    LAYOUT_ITEM_FILEPATH,
    LAYOUT_ITEM_POSITION_X,
    LAYOUT_ITEM_POSITION_Y,
    LAYOUT_ITEM_SIZE_WIDTH,
    LAYOUT_ITEM_SIZE_HEIGHT,
    LAYOUT_ITEM_ROTATED_DEGREES,
    LAYOUT_ITEM_RESERVATION_POSITION_X,
    LAYOUT_ITEM_RESERVATION_POSITION_Y,
    LAYOUT_ITEM_RESERVATION_SIZE_WIDTH,
    LAYOUT_ITEM_RESERVATION_SIZE_HEIGHT,
    LAYOUT_ITEM_RESERVATION_NO,
    LAYOUT_ITEM_LATENCY,
    LAYOUT_ITEM_TYPE
]
LAYOUT_ITEM_HEADER_HELP = [
    LAYOUT_ITEM_FILEPATH_HELP,
    LAYOUT_ITEM_POSITION_X_HELP,
    LAYOUT_ITEM_POSITION_Y_HELP,
    LAYOUT_ITEM_SIZE_WIDTH_HELP,
    LAYOUT_ITEM_SIZE_HEIGHT_HELP,
    LAYOUT_ITEM_ROTATED_DEGREES_HELP,
    LAYOUT_ITEM_RESERVATION_POSITION_X_HELP,
    LAYOUT_ITEM_RESERVATION_POSITION_Y_HELP,
    LAYOUT_ITEM_RESERVATION_SIZE_WIDTH_HELP,
    LAYOUT_ITEM_RESERVATION_SIZE_HEIGHT_HELP,
    LAYOUT_ITEM_RESERVATION_NO_HELP,
    LAYOUT_ITEM_LATENCY_HELP,
    LAYOUT_ITEM_TYPE_HELP
]
LAYOUT_CSV_HEADERS = [
    *LAYOUT_HEADERS,
    *LAYOUT_CANVAS_HEADERS,
    *LAYOUT_CONTOUR_HEADERS,
    *LAYOUT_ITEM_HEADERS,
]
LAYOUT_CSV_HEADER_HELP = [
    *LAYOUT_HEADERS_HELP,
    *LAYOUT_CANVAS_HEADER_HELP,
    *LAYOUT_CONTOUR_HEADER_HELP,
    *LAYOUT_ITEM_HEADER_HELP,
]

LAYOUT_CSV_FILE_HELP = '''csv file representing 1 Layout Contour, 1 Layout Canvas and N Layout Items:
"{0}"
{1}
'''.format(
    '","'.join(LAYOUT_CSV_HEADERS),
    ','.join(LAYOUT_CSV_HEADER_HELP)
)